- name: openrouter/anthropic/claude-3.5-sonnet
  extra_params:
    extra_body:
      provider:
        order: ["Anthropic"]
        allow_fallbacks: false
- name: openrouter/anthropic/claude-3.5-sonnet
  extra_params:
    extra_body:
      provider:
        order: ["Anthropic"]
        allow_fallbacks: false
- name: openrouter/deepseek/deepseek-r1
  extra_params:
    extra_body:
      provider:
        order: ["Fireworks"]
        allow_fallbacks: false
- name: openrouter/deepseek/deepseek-chat
  extra_params:
    extra_body:
      provider:
        order: ["Fireworks"]
        allow_fallbacks: false
