- name: gemini/gemini-2.5-pro-preview-06-05
  overeager: true
  edit_format: diff-fenced
  use_repo_map: true
  weak_model_name: gemini/gemini-2.5-flash-preview-04-17
  accepts_settings: ["reasoning_effort", "thinking_tokens"]
