## Enable caching of prompts (default: False)
#cache-prompts: true
## Enable/disable auto commit of LLM changes (default: True)
#auto-commits: false
## Specify the api base url
#openai-api-base: https://glhf.chat/api/openai/v1
## Specify the model to use for the main chat
model: openai/gpt-4o-2024-11-20
#model: openai/hf:Qwen/Qwen2.5-Coder-32B-Instruct
## Specify the model to use for editor tasks (default depends on --model)
editor-model: deepseek/deepseek-coder
## Specify a custom prompt for generating commit messages
commit-prompt: |
  You are an expert software engineer that generates concise, one-line Git commit messages based on the provided diffs.
  Review the provided context and diffs which are about to be committed to a git repo.
  Review the diffs carefully.
  Generate a one-line commit message for those changes.
  The commit message should be structured as follows: <type>: <description>
  Use these for <type>: fix, feat, build, chore, ci, docs, style, refactor, perf, test

  Ensure the commit message:
  - Starts with the appropriate prefix.
  - Is in the imperative mood (e.g., "add feature" not "added feature" or "adding feature").
  - Does not exceed 72 characters.

  Reply only with the one-line commit message, without any additional text, explanations, or line breaks.
