alias:
  - "3.7:openrouter/anthropic/claude-3.7-sonnet"
  - "3.5:openrouter/anthropic/claude-3.5-sonnet"
  - "r1:openrouter/deepseek/deepseek-r1"
  - "o3:openrouter/openai/o3-mini-high"
  - "v3:openrouter/deepseek/deepseek-chat"
cache-prompts: true
code-theme: "coffee"
commit-prompt: |
  You are an expert software engineer that generates concise, one-line Git commit messages based on the provided diffs.
  Review the provided context and diffs which are about to be committed to a git repo.
  Review the diffs carefully.
  Generate a one-line commit message for those changes.
  The commit message should be structured as follows: <type>: <description>
  Use these for <type>: fix, feat, build, chore, ci, docs, style, refactor, perf, test

  Ensure the commit message:
  - Starts with the appropriate prefix.
  - Is in the imperative mood (e.g., "add feature" not "added feature" or "adding feature").
  - Does not exceed 72 characters.
  - Do not start with a capital letter.

  Reply only with the one-line commit message, without any additional text, explanations, or line breaks.
completion-menu-color: "#11111b"
model: v3
notifications: true
watch-files: true
