tap "stripe/stripe-cli"

brew "antidote"
brew "bat"
brew "biome"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "lazygit"
brew "mise"
brew "neovim"
brew "stow"
brew "stripe/stripe-cli/stripe"
brew "tealdeer"
brew "tmux"
brew "zoxide"

if OS.mac?
  cask "aqua-voice"
  cask "bitwarden"
  cask "brave-browser"
  cask "gcloud-cli"
  cask "ghostty"
  cask "karabiner-elements"
  cask "nextcloud"
  cask "raycast"
  cask "tailscale-app"
  cask "telegram"
end
