brew "biome"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "jq"
brew "lazygit"
brew "mise"
brew "powerlevel10k"
brew "ripgrep"
brew "stow"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

if OS.mac?
  cask "brave-browser"
  cask "ghostty"
  cask "tailscale-app"
  cask "wispr-flow"
  cask "zed"
end
