[font]
size = 11.0

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[window]
padding = { x = 4, y = 4 }
