set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

set -g base-index 1
set -g detach-on-destroy off
set -g mouse on
set -g pane-base-index 1
set -g prefix C-a
set -g renumber-windows on
set -g set-clipboard on

set-window-option -g mode-keys vi

unbind C-b
bind C-a send-prefix
bind g display-popup -E -w 62% -h 38% -b rounded -S "fg=#7C7086" "tms"

bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

set -g status-bg black
set -g status-fg white
set -g status-interval 5
set -g status-left-length 90
set -g status-position top
set -g status-right ''
set -g status-right-length 60

run '$HOME/.config/tmux/plugins/tpm/tpm'
