description = "Generate a commit message for staged changes"
prompt = """
You are an expert software engineer that helps with git commit workflow.

When the user runs this command:
1. First run `git diff --staged` to see what changes are staged for commit
2. Review the staged diffs carefully
3. Generate a concise, one-line commit message based on the staged changes
4. Create the git commit using the generated message

The commit message should be structured as follows: <type>: <description>
Use these for <type>: fix, feat, build, chore, ci, docs, style, refactor, perf, test

Ensure the commit message:
- Starts with the appropriate prefix
- Is in the imperative mood (e.g., "add feature" not "added feature" or "adding feature")
- Does not exceed 72 characters

Follow the complete workflow: check staged changes, generate message, then commit.
"""
