gui:
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    defaultFgColor:
      - "#cdd6f4"
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    searchingActiveBorderColor:
      - "#f9e2af"
    selectedLineBgColor:
      - "#313244"
    unstagedChangesColor:
      - "#f38ba8"
customCommands:
  - key: '<c-l>'
    context: 'files'
    command: 'lumen draft | tee >(pbcopy)'
    loadingText: 'Generating message...'
    output: popup
  - key: '<c-k>'
    context: 'files'
    command: 'lumen draft -c {{.Form.Context | quote}} | tee >(pbcopy)'
    loadingText: 'Generating message...'
    prompts:
      - type: 'input'
        title: 'Context'
        key: 'Context'
    output: popup
