gui:
  showBottomLine: false
os:
  edit: "cursor --reuse-window -- {{filename}}"
  editAtLine: "cursor --reuse-window --goto -- {{filename}}:{{line}}"
  editAtLineAndWait: "cursor --reuse-window --goto --wait -- {{filename}}:{{line}}"
  openDirInEditor: "cursor -- {{dir}}"
  editInTerminal: false
