[[session]]
name = "influencer-client"
path = "~/Developer/influencer-client"

[[session]]
name = "influencer-admin"
path = "~/Developer/influencer-admin"

[[session]]
name = "dsp-master-client"
path = "~/Developer/dsp-master-client"

[[session]]
name = "tarot-mobile"
path = "~/Developer/tarot-mobile"

[[session]]
name = "tarot-backend"
path = "~/Developer/tarot-backend"

[[session]]
name = "practical-vim"
path = "~/Developer/practical-vim"
