[[session]]
name = "influencer-client"
path = "~/Developer/influencer-client"

[[session]]
name = "influencer-admin"
path = "~/Developer/influencer-admin"

[[session]]
name = "dsp-master-client"
path = "~/Developer/dsp-master-client"

[[session]]
name = "flashcard-web"
path = "~/Developer/flashcard-web"

[[session]]
name = "tarot-mobile"
path = "~/Developer/tarot-mobile"

[[session]]
name = "tarot-cms"
path = "~/Developer/tarot-cms"

[[session]]
name = "practical-vim"
path = "~/Developer/practical-vim"
