#!/usr/bin/env bash
set -euo pipefail

# Sets up the GNOME desktop the way I keep it:
#   - dock favorites: fixed set and order
#   - app grid (overview): sorted alphabetically
#   - dock app icons: normalized to a consistent visual size
# Everything outside the dock keeps its stock icon on purpose.

[ "$(uname -s)" = "Linux" ] || {
  echo "setup-gnome-desktop: not Linux, skipping."
  exit 0
}

# --- Dock favorites + app grid order -----------------------------------------
# Declarative: this IS the dock (contents + order). app-picker-layout="[]"
# resets the overview grid to alphabetical auto-sort (folders are preserved).
FAVORITES="['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'firefox_firefox.desktop', 'com.mitchellh.ghostty.desktop', 'dev.zed.Zed.desktop']"

if command -v gsettings >/dev/null 2>&1; then
  gsettings set org.gnome.shell favorite-apps "$FAVORITES" 2>/dev/null \
    && echo "setup-gnome-desktop: dock favorites set." \
    || echo "setup-gnome-desktop: could not set favorites (no GNOME session?)." >&2
  gsettings set org.gnome.shell app-picker-layout "[]" 2>/dev/null \
    && echo "setup-gnome-desktop: app grid set to alphabetical." \
    || true
fi

# --- Dock app icon normalization ---------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHROME_MASTER="$SCRIPT_DIR/assets/google-chrome-2022.png"
VENV="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles-icons/venv"

pick_python() {
  if [ -x "$VENV/bin/python" ] && "$VENV/bin/python" -c "import PIL" >/dev/null 2>&1; then
    echo "$VENV/bin/python"; return 0
  fi
  if python3 -c "import PIL" >/dev/null 2>&1; then
    command -v python3; return 0
  fi
  echo "setup-gnome-desktop: setting up Pillow venv..." >&2
  rm -rf "$VENV"
  if python3 -m venv "$VENV" >/dev/null 2>&1 \
    && "$VENV/bin/pip" install --quiet --upgrade pip \
    && "$VENV/bin/pip" install --quiet pillow; then
    echo "$VENV/bin/python"; return 0
  fi
  return 1
}

PYTHON="$(pick_python)" || {
  echo "setup-gnome-desktop: no Python with Pillow found (install python3-pil or python3-venv); skipping icons." >&2
  exit 0
}

CHROME_MASTER="$CHROME_MASTER" "$PYTHON" - <<'PY'
import glob
import os
import re
import shutil
from PIL import Image

HOME = os.path.expanduser("~")
SYS = "/usr/share/icons"
DST = os.path.join(HOME, ".local/share/icons")
chrome_master = os.environ["CHROME_MASTER"]
# Stamped into desktop overrides we generate, so a rerun knows it owns the file
# and may overwrite it — but never clobbers a hand-written user override.
MARKER = "# generated by dotfiles setup-gnome-desktop"

def fit(img, size, target):
    # Crop to the artwork's opaque bounds, scale so its longest side fills
    # `target` (a 0-1 fraction) of the size×size icon box, and center it on a
    # transparent square. `target` is tuned per app because apps ship art with
    # different built-in padding; normalizing it makes the dock icons look the
    # same visual size next to each other.
    img = img.crop(img.split()[3].getbbox())
    cw, ch = img.size
    scale = (target * size) / max(cw, ch)
    nw, nh = max(1, round(cw * scale)), max(1, round(ch * scale))
    content = img.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(content, ((size - nw) // 2, (size - nh) // 2), content)
    return canvas

def ensure_theme(theme):
    src = os.path.join(SYS, theme, "index.theme")
    dst_dir = os.path.join(DST, theme)
    os.makedirs(dst_dir, exist_ok=True)
    dst = os.path.join(dst_dir, "index.theme")
    if os.path.exists(src) and not os.path.exists(dst):
        shutil.copy(src, dst)

def numeric_size_dir(path):
    sizedir = os.path.basename(os.path.dirname(os.path.dirname(path)))
    base = sizedir.split("@")[0]
    if not re.match(r"^\d+x\d+$", base):
        return None
    width, height = (int(part) for part in base.split("x", 1))
    if width != height:
        return None
    return sizedir, width

def write_normalized_icon(src, theme, sizedir, size, name, target):
    try:
        im = Image.open(src).convert("RGBA")
        if im.getbbox() is None:
            return False
    except Exception:
        return False
    out = os.path.join(DST, theme, sizedir, "apps")
    os.makedirs(out, exist_ok=True)
    fit(im, size, target).save(os.path.join(out, f"{name}.png"))
    return True

def write_desktop_icon(src, dst, icon_name, keep_user_override=False):
    # Copy/rewrite a .desktop while only swapping Icon= in [Desktop Entry].
    # Exec= and everything else is preserved verbatim.
    if not os.path.exists(src):
        return False
    if keep_user_override and os.path.exists(dst):
        try:
            with open(dst, encoding="utf-8") as fh:
                if MARKER not in fh.read():
                    return False  # hand-written override — leave it alone
        except OSError:
            return False
    try:
        with open(src, encoding="utf-8") as fh:
            lines = fh.readlines()
    except OSError:
        return False
    out = [MARKER + "\n"]
    section = None
    for line in lines:
        if line == MARKER + "\n":
            continue
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped
        if section == "[Desktop Entry]" and re.match(r"^\s*Icon\s*=", line):
            out.append("Icon=%s\n" % icon_name)
        else:
            out.append(line)
    try:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "w", encoding="utf-8") as fh:
            fh.writelines(out)
    except OSError:
        return False
    return True

# Google Chrome: ships a flat 2022 logo with no transparent padding, so we
# normalize from a bundled master PNG instead of the installed icon.
master = Image.open(chrome_master).convert("RGBA")
for s in (16, 24, 32, 48, 64, 128, 256):
    out = os.path.join(DST, f"hicolor/{s}x{s}/apps")
    os.makedirs(out, exist_ok=True)
    fit(master, s, 0.91).save(os.path.join(out, "google-chrome.png"))

# Zed: installs a large absolute icon path in its user .desktop file, so create
# normalized hicolor icons and point the launcher at the themed name below.
for src in sorted(glob.glob(os.path.join(HOME, ".local/zed.app/share/icons/hicolor/*/apps/zed.png"))):
    parsed = numeric_size_dir(src)
    if not parsed:
        continue
    sizedir, size = parsed
    write_normalized_icon(src, "hicolor", sizedir, size, "zed", 0.96)

# (theme, icon names, fill target) — see fit() for what the target fraction means.
JOBS = [
    ("hicolor", ["firefox"],                          1.00),
    ("hicolor", ["com.mitchellh.ghostty"],            0.90),
    ("Yaru",    ["org.gnome.Nautilus", "nautilus"],   0.955),
]
for theme, names, target in JOBS:
    count = 0
    for name in names:
        for src in sorted(glob.glob(f"{SYS}/{theme}/*/apps/{name}.png")):
            parsed = numeric_size_dir(src)
            if not parsed:
                continue
            sizedir, size = parsed
            if write_normalized_icon(src, theme, sizedir, size, name, target):
                count += 1
    if count:
        ensure_theme(theme)

# The dock's Firefox is the snap, whose Icon= is an absolute path — so the
# themed 'firefox' icon normalized above never reaches it. Point a user-level
# .desktop override at that themed name. Deliberately scoped to this one app.
firefox_src = "/var/lib/snapd/desktop/applications/firefox_firefox.desktop"
firefox_dst = os.path.join(HOME, ".local/share/applications", os.path.basename(firefox_src))
if write_desktop_icon(firefox_src, firefox_dst, "firefox", keep_user_override=True):
    print("  firefox (snap): pointed at normalized themed icon via .desktop override")
zed_desktop = os.path.join(HOME, ".local/share/applications/dev.zed.Zed.desktop")
if write_desktop_icon(zed_desktop, zed_desktop, "zed"):
    print("  zed: pointed at normalized themed icon via .desktop override")
PY

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  for theme in hicolor Yaru; do
    dir="$HOME/.local/share/icons/$theme"
    [ -d "$dir" ] && gtk-update-icon-cache -f -t "$dir" >/dev/null 2>&1 || true
  done
fi

# Register the Firefox .desktop override.
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true
fi

echo "setup-gnome-desktop: done. Log out/in for GNOME Shell to refresh."
