#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/log.sh"

[ "$(uname -s)" = "Linux" ] || exit 0

FAVORITES="['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'firefox_firefox.desktop', 'com.mitchellh.ghostty.desktop', 'code.desktop', 'android-studio.desktop', 't3-code.desktop', 'lens.desktop', 'bruno.desktop']"

if command -v gsettings >/dev/null 2>&1; then
  gsettings set org.gnome.shell favorite-apps "$FAVORITES" 2>/dev/null &&
    log "set dock favorites" || warn "could not set dock favorites"
  gsettings set org.gnome.shell app-picker-layout "[]" 2>/dev/null &&
    log "set alphabetical app grid" || true
fi

CHROME_MASTER="$SCRIPT_DIR/assets/google-chrome-2022.png"
VENV="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles-icons/venv"

pick_python() {
  if [ -x "$VENV/bin/python" ] && "$VENV/bin/python" -c "import PIL" >/dev/null 2>&1; then
    printf '%s\n' "$VENV/bin/python"; return 0
  fi
  python3 -c "import PIL" >/dev/null 2>&1 && { command -v python3; return 0; }
  log "setting up Pillow environment" >&2
  rm -rf "$VENV"
  python3 -m venv "$VENV" >/dev/null 2>&1 && "$VENV/bin/pip" install --quiet --upgrade pip && "$VENV/bin/pip" install --quiet pillow && { printf '%s\n' "$VENV/bin/python"; return 0; }
  return 1
}

PYTHON="$(pick_python)" || {
  warn "Pillow unavailable; skipping icons"
  exit 0
}

CHROME_MASTER="$CHROME_MASTER" "$PYTHON" - <<'PY'
import glob
import os
import re
import shutil
from PIL import Image

HOME = os.path.expanduser("~")
SYS = "/usr/share/icons"
DST = os.path.join(HOME, ".local/share/icons")
chrome_master = os.environ["CHROME_MASTER"]
MARKER = "# generated by dotfiles setup-gnome-desktop"

def fit(img, size, target):
    img = img.crop(img.split()[3].getbbox())
    cw, ch = img.size
    scale = (target * size) / max(cw, ch)
    nw, nh = max(1, round(cw * scale)), max(1, round(ch * scale))
    content = img.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(content, ((size - nw) // 2, (size - nh) // 2), content)
    return canvas

def ensure_theme(theme):
    src = os.path.join(SYS, theme, "index.theme")
    dst_dir = os.path.join(DST, theme)
    os.makedirs(dst_dir, exist_ok=True)
    dst = os.path.join(dst_dir, "index.theme")
    if os.path.exists(src) and not os.path.exists(dst):
        shutil.copy(src, dst)

def numeric_size_dir(path):
    sizedir = os.path.basename(os.path.dirname(os.path.dirname(path)))
    base = sizedir.split("@")[0]
    if not re.match(r"^\d+x\d+$", base):
        return None
    width, height = (int(part) for part in base.split("x", 1))
    if width != height:
        return None
    return sizedir, width

def write_normalized_icon(src, theme, sizedir, size, name, target):
    try:
        im = Image.open(src).convert("RGBA")
        if im.getbbox() is None:
            return False
    except Exception:
        return False
    out = os.path.join(DST, theme, sizedir, "apps")
    os.makedirs(out, exist_ok=True)
    fit(im, size, target).save(os.path.join(out, f"{name}.png"))
    return True

def write_desktop_icon(src, dst, icon_name, keep_user_override=False, startup_wm_class=None, no_display=False):
    if not os.path.exists(src):
        return False
    if keep_user_override and os.path.exists(dst):
        try:
            with open(dst, encoding="utf-8") as fh:
                if MARKER not in fh.read():
                    return False
        except OSError:
            return False
    try:
        with open(src, encoding="utf-8") as fh:
            lines = fh.readlines()
    except OSError:
        return False
    out = [MARKER + "\n"]
    section = None
    saw_no_display = False
    for line in lines:
        if line == MARKER + "\n":
            continue
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped
        if section == "[Desktop Entry]" and re.match(r"^\s*Icon\s*=", line):
            out.append("Icon=%s\n" % icon_name)
        elif startup_wm_class and section == "[Desktop Entry]" and re.match(r"^\s*StartupWMClass\s*=", line):
            out.append("StartupWMClass=%s\n" % startup_wm_class)
        elif no_display and section == "[Desktop Entry]" and re.match(r"^\s*NoDisplay\s*=", line):
            out.append("NoDisplay=true\n")
            saw_no_display = True
        else:
            out.append(line)
    if no_display and not saw_no_display:
        for i, line in enumerate(out):
            if line.strip() == "[Desktop Entry]":
                out.insert(i + 1, "NoDisplay=true\n")
                break
    try:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "w", encoding="utf-8") as fh:
            fh.writelines(out)
    except OSError:
        return False
    return True

def write_handy_tray_icon(src, dst):
    if not os.path.exists(src):
        return False
    try:
        im = Image.open(src).convert("RGBA")
        bbox = im.split()[3].getbbox()
        if bbox is None:
            return False
        content = im.crop(bbox)
    except Exception:
        return False
    scale = 62 / max(content.size)
    nw, nh = max(1, round(content.width * scale)), max(1, round(content.height * scale))
    content = content.resize((nw, nh), Image.LANCZOS)
    canvas = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    canvas.paste(content, ((64 - nw) // 2, (64 - nh) // 2), content)
    try:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        canvas.save(dst)
    except OSError:
        return False
    return True

master = Image.open(chrome_master).convert("RGBA")
for s in (16, 24, 32, 48, 64, 128, 256):
    out = os.path.join(DST, f"hicolor/{s}x{s}/apps")
    os.makedirs(out, exist_ok=True)
    fit(master, s, 0.91).save(os.path.join(out, "google-chrome.png"))

t3_sources = [
    os.path.join(DST, "t3-code.png"),
    os.path.join(DST, "t3-code.xpm"),
]
for t3_source in t3_sources:
    if not os.path.exists(t3_source):
        continue
    try:
        t3_master = Image.open(t3_source).convert("RGBA")
    except Exception:
        continue
    for s in (16, 24, 32, 48, 64, 128, 256, 512):
        out = os.path.join(DST, f"hicolor/{s}x{s}/apps")
        os.makedirs(out, exist_ok=True)
        fit(t3_master, s, 0.94).save(os.path.join(out, "t3-code.png"))
    ensure_theme("hicolor")
    break

JOBS = [
    ("hicolor", ["firefox"],                          1.00),
    ("hicolor", ["com.mitchellh.ghostty"],            0.90),
    ("hicolor", ["lens-desktop"],                     0.98),
    ("Yaru",    ["org.gnome.Nautilus", "nautilus"],   0.955),
]
for theme, names, target in JOBS:
    count = 0
    for name in names:
        for src in sorted(glob.glob(f"{SYS}/{theme}/*/apps/{name}.png")):
            parsed = numeric_size_dir(src)
            if not parsed:
                continue
            sizedir, size = parsed
            if write_normalized_icon(src, theme, sizedir, size, name, target):
                count += 1
    if count:
        ensure_theme(theme)

firefox_src = "/var/lib/snapd/desktop/applications/firefox_firefox.desktop"
firefox_dst = os.path.join(HOME, ".local/share/applications", os.path.basename(firefox_src))
if write_desktop_icon(firefox_src, firefox_dst, "firefox", keep_user_override=True):
    print("setup-gnome-desktop: updated Firefox icon")
t3_desktop = os.path.join(HOME, ".local/share/applications/t3-code.desktop")
if write_desktop_icon(t3_desktop, t3_desktop, "t3-code"):
    print("setup-gnome-desktop: updated T3 Code icon")
lens_src = "/usr/share/applications/lens-desktop.desktop"
lens_apps = os.path.join(HOME, ".local/share/applications")
lens_dst = os.path.join(lens_apps, "lens.desktop")
if write_desktop_icon(lens_src, lens_dst, "lens-desktop", startup_wm_class="lens"):
    print("setup-gnome-desktop: created lens.desktop")
lens_hide = os.path.join(lens_apps, "lens-desktop.desktop")
if write_desktop_icon(lens_src, lens_hide, "lens-desktop", startup_wm_class="lens", no_display=True):
    print("setup-gnome-desktop: hid duplicate lens-desktop.desktop")

handy_resource_dir = "/usr/lib/Handy/resources"
handy_staging_dir = os.path.join(HOME, ".local/share/handy-tray-icon-fix")
handy_names = ["handy.png", "recording.png", "transcribing.png"]
handy_staged = []
handy_installed = []
for name in handy_names:
    src = os.path.join(handy_resource_dir, name)
    staged = os.path.join(handy_staging_dir, name)
    if not write_handy_tray_icon(src, staged):
        continue
    handy_staged.append(name)
    if os.access(src, os.W_OK) and write_handy_tray_icon(src, src):
        handy_installed.append(name)
if handy_installed:
    print("setup-gnome-desktop: enlarged Handy tray icons")
elif handy_staged:
    print("setup-gnome-desktop: staged Handy tray icons in ~/.local/share/handy-tray-icon-fix")
    print("setup-gnome-desktop: install them with:")
    for name in handy_staged:
        print(f"    sudo cp {os.path.join(handy_staging_dir, name)} {os.path.join(handy_resource_dir, name)}")
PY

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  for theme in hicolor Yaru; do
    dir="$HOME/.local/share/icons/$theme"
    [ -d "$dir" ] && gtk-update-icon-cache -f -t "$dir" >/dev/null 2>&1 || true
  done
fi

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true
fi

log "configured desktop"
