general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Jetbrains Mono"

[font.offset]
y = 3

[window]
option_as_alt = "Both"

[window.padding]
x = 4
y = 4
