import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Medium Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Medium Regular"

[window]
padding = { x = 4, y = 4 }
option_as_alt = "Both"
dynamic_title = false
