import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "MonoLisa Nerd Font" }

[window]
option_as_alt = "Both"
dynamic_title = false
startup_mode = "Maximized"

[mouse]
hide_when_typing = true
