live_config_reload = true
shell = { program = "/home/linuxbrew/.linuxbrew/bin/fish", args = ["--login"] }

[env]
TERM = "xterm-256color"

[font.normal]
family = "MonoLisa Nerd Font"

[font.offset]
y = 0

[window]
option_as_alt = "Both"
padding = { x = 4, y = 2 }

dynamic_title = false

[scrolling]
multiplier = 0
