import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "MonoLisa Nerd Font", style = "Medium Regular" }
italic = { style = "Medium Italic" }

[window]
padding = { x = 4, y = 4 }
option_as_alt = "Both"
dynamic_title = false

[mouse]
hide_when_typing = true
