general.import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MonoLisa"

[window]
option_as_alt = "Both"

[window.padding]
x = 4
y = 4
