[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal.family = "MonoLisa Nerd Font"

[window]
dynamic_padding = true
padding.x = 8
padding.y = 8
decorations = "None"
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b[13;2u"
