general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MonoLisa Nerd Font"

[font.offset]
y = 1

[window]
option_as_alt = "Both"
padding = { x = 4, y = 2 }

[scrolling]
multiplier = 0
