general.import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"

[window.padding]
x = 4
y = 4
