import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MonoLisa", style = "Regular" }

[window]
padding = { x = 8, y = 8 }
option_as_alt = "Both"
dynamic_title = false
