[[keyboard.bindings]]
chars = "\u0002 "
key = "C"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Option|Shift"

[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002s"
key = "S"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0002p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002p"
key = "{"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Option"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Option"
