alias lg="lazygit"
alias ld="lazydocker"
alias ?="gh copilot explain"
alias ??="gh copilot suggest"
alias s="sudo wg show"
alias u="wg-quick up ~/Sync/wg0.conf"
alias d="wg-quick down ~/Sync/wg0.conf"
