[tools]
bun = "latest"
node = { version = "lts", postinstall = "corepack enable" }
go = "latest"

"npm:@antfu/ni" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@openai/codex" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
npm.bun = true
